blog/blog/urls.py
from django.urls import path
from . import views, controllers


app_name = 'blog'
urlpatterns = [
    path('', views.articles, name='index'),
    path('<int:page_index>', views.articles, name='index'),
    path('signIn', views.sign_in, name='signIn'),
    path('signUp', views.sign_up, name='signUp'),
    path('create', views.create, name='create'),

    path('profile/<str:username>', views.profile, name='profile'),
    path('edit/<str:article_id>', views.edit, name='edit'),
    path('article/<str:article_id>', views.article, name='article'),
    path('my/', views.my_articles, name='myArticles'),
    path('my/<int:page_index>', views.my_articles, name='myArticles'),

    path('action/signOut', controllers.sign_out, name='actionSignOut'),
    path('action/signIn', controllers.sign_in, name='actionSignIn'),
    path('action/signUp', controllers.sign_up, name='actionSignUp'),
    path('action/changePassword', controllers.change_pass, name='actionChangePassword'),
    path('action/deleteAccount', controllers.delete_user, name='actionDeleteAccount'),
    path('action/createArticle', controllers.create_article, name='actionCreateArticle'),
    path('action/createComment/<str:public_id>', controllers.create_comment, name='actionCreateComment'),
    path('action/deleteArticle/<str:public_id>', controllers.delete_article, name='actionDeleteArticle'),
    path('action/editArticle/<str:article_id>', controllers.edit_article, name='actionEditArticle'),
]

yetAnotherCMS/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "yetAnotherCMS"
urlpatterns = [
    path('', include('blog.blog.urls')),
    path('admin/', admin.site.urls),
]

blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    name = models.CharField(max_length=70)
    public_id = models.CharField(max_length=40)
    publish_date = models.DateField('date of publish')
    content = models.TextField(max_length=3000)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)

    def __str__(self):
        return self.text

blog/blog/controllers.py
from django.db import IntegrityError
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .models import Article, Comment
from uuid import uuid4
from django.utils import timezone
from django.http.response import HttpResponseNotAllowed


def sign_in(request):
    email = request.POST.get('email', '')
    passwd = request.POST.get('password', '')
    user = authenticate(request, username=email, password=passwd)
    if user is not None:
        login(request, user)
        return redirect('blog:index')
    else:
        return redirect('blog:signIn')


def sign_up(request):
    # create a user
    email = request.POST['email']
    passwd = request.POST['password']
    try:
        user = User.objects.create_user(email, email, passwd)
        user.save()
    except IntegrityError:
        # redirect if login exists
        return redirect('blog:signUp')
    # sign in
    user = authenticate(request, username=email, password=passwd)
    if user is not None:
        login(request, user)
        return redirect('blog:index')
    else:
        return redirect('blog:signUp')


def sign_out(request):
    logout(request)
    return redirect('blog:index')


def delete_user(request):
    user = request.user
    password = request.POST.get('password', '')
    if not user.is_authenticated or not user.check_password(password):
        return redirect('blog:profile', username=user.username)
    user.delete()
    return redirect('blog:index')


def change_pass(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseNotAllowed('user is not authed')
    old_password = request.POST.get('oldPassword', '')
    new_password = request.POST.get('newPassword', '')

    if user.check_password(old_password):
        user.set_password(new_password)
        user.save()
        update_session_auth_hash(request, user)
    return redirect('blog:profile', username=user.username)


def create_article(request):
    # redirect if not authed
    if not request.user.is_authenticated:
        return HttpResponseNotAllowed('user is not authed')
    # create an article
    name = request.POST.get('article_name', '')
    content = request.POST.get('article_text', '')
    a = Article(name=name, content=content, author=request.user, public_id=uuid4().hex, publish_date=timezone.now())
    a.save()
    return redirect('blog:edit', article_id=a.public_id)


def edit_article(request, article_id):
    # redirect if not authed
    if not request.user.is_authenticated:
        return HttpResponseNotAllowed('user is not authed')
    a = get_object_or_404(Article, public_id=article_id)
    # redirect if user is not the author
    if a.author != request.user:
        return HttpResponseNotAllowed('user is not owner')
    # edit the article
    a.name = request.POST.get('article_name', a.name)
    a.content = request.POST.get('article_text', a.content)
    a.save()
    return redirect('blog:edit', article_id=article_id)


def delete_article(request, public_id):
    a = get_object_or_404(Article, public_id=public_id)

    if request.user == a.author:
        a.delete()
        return redirect('blog:myArticles')
    else:
        return HttpResponseNotAllowed('user is not owner')


def create_comment(request, public_id):
    if not request.user.is_authenticated:
        return HttpResponseNotAllowed('user is not authed')

    c = Comment(author=request.user,
                article=get_object_or_404(Article, public_id=public_id),
                text=request.POST.get('comment_text', ''))
    c.save()

    return redirect('blog:article', article_id=public_id)

blog/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from django.contrib.auth.models import User
from django.core.paginator import Paginator


def create(request):
    if not request.user.is_authenticated:
        return redirect('blog:signIn')

    return render(request, 'blog/editor.html', {'user': request.user, 'action': 'create'})


def edit(request, article_id):
    # redirect if not authed
    if not request.user.is_authenticated:
        return redirect('/signIn')
    # get an article
    a = get_object_or_404(Article, public_id=article_id)
    # redirect if user is not the author
    if a.author != request.user:
        return redirect('blog:index')

    return render(request, 'blog/editor.html', {'user': request.user, 'action': 'edit', 'article': a})


def article(request, article_id):
    a = get_object_or_404(Article, public_id=article_id)
    cs = Comment.objects.filter(article=a).order_by('-id')
    return render(request, 'blog/article.html', {'user': request.user, 'article': a, 'comments': cs})


def articles(request, page_index=1):
    p = Paginator(Article.objects.order_by('-id'), 10)
    page = p.get_page(page_index)
    return render(request, 'blog/browse.html', {'user': request.user, 'page': page})


def my_articles(request, page_index=1):
    if not request.user.is_authenticated:
        return redirect('/signIn')

    a = Article.objects.filter(author=request.user).order_by('-id')
    p = Paginator(a, 10)
    page = p.get_page(page_index)
    return render(request, 'blog/browse.html', {'user': request.user, 'page': page, 'my': True})


def sign_in(request):
    return render(request, 'blog/signIn.html', {'user': request.user})


def sign_up(request):
    return render(request, 'blog/signUp.html', {'user': request.user})


def profile(request, username):
    user = get_object_or_404(User, username=username)
    stat = {
        'article_count': Article.objects.filter(author=user).count(),
        'comment_count': Comment.objects.filter(author=user).count(),
    }

    return render(request, 'blog/profile.html', {'user': request.user, 'stat': stat, 'profile_owner': user})

blog/templates/blog/article.html
{% extends "./base.html" %}
{% block content %}
<div class="container-sm mt-5" style="max-width: 700px">
    <div class="mb-3">
        <h1>{{ article.name }}</h1>
    </div>
    <div class="mb-5">
        <h4 class="text-body-secondary">Author: <a class="text-decoration-none" href="{% url 'blog:profile' article.author.username %}">{{ article.author.username }}</a></h4>
        <h4 class="text-body-secondary">Date: {{ article.publish_date }}</h4>
    </div>
    <div class="mb-5">
        <p class="fs-5">{{ article.content }}</p>
    </div>
    <div class="mb-3">
        <h2>Comments</h2>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'blog:actionCreateComment' article.public_id %}">
                {% csrf_token %}
                <textarea
                    maxlength="300"
                    rows="2"
                    required
                    autocomplete="off"
                    name="comment_text"
                    class="form-control mb-2"
                    id="comment_text"
                ></textarea>
                <button type="submit" class="btn btn-primary">Leave a comment</button>
            </form>
        {% endif %}
        <div class="d-flex justify-content-start flex-column mt-4">
            {% for comment in comments %}
            <div class="card mb-3">
                <div class="card-header">{{ comment.author }}</div>
                <div class="card-body">
                    <p class="card-text fs-6">{{ comment.text }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>Blog</title>
       {% load static %}
     <link rel="stylesheet" href="{% static '/blog/bootstrap.min.css' %}">
   </head>
   <body>
      <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Blog</a>
          <div class="d-flex justify-content-evenly">
              {% if user.is_authenticated %}
              <a href="{% url 'blog:myArticles' %}" class="btn btn-outline-light m-1">My articles</a>
              <a href="{% url 'blog:create' %}" class="btn btn-outline-light m-1">Create</a>
                <a href="{% url 'blog:profile' user.username %}" class="btn btn-outline-light m-1">{{ user.username }}</a>
                <form action="{% url 'blog:actionSignOut' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-light m-1" type="submit">Logout</button>
                </form>
              {% endif %}
              {% if not user.is_authenticated %}
                <a href="/signIn" class="btn btn-outline-light m-1">Sign in</a>
                <a href="/signUp" class="btn btn-outline-light m-1">Sign up</a>
              {% endif %}
          </div>
        </div>
      </nav>
        {% block content %}
        {% endblock %}
   </body>
</html>

blog/templates/blog/browse.html
{% extends "./base.html" %}
{% block content %}
<div class="d-flex justify-content-center align-items-center flex-wrap w-75 m-auto mt-1">
  {% for article in page %}
    <div class="card m-2" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{ article.name }}</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">
          {% if article.author.username != None %}
          Author: <a class="text-decoration-none" href="{% url 'blog:profile' article.author.username %}">{{ article.author.username }}</a>
          <br>
          {% endif %}
          Date: {{ article.publish_date }}
        </h6>
        <p class="card-text">{{ article.content|slice:"0:50" }}...</p>
        <div class="">
          <a href="{% url 'blog:article' article.public_id %}" class="btn btn-primary">Read</a>
          {% if my %}
          <a href="{% url 'blog:edit' article.public_id %}" class="btn btn-success">Edit</a>
          <form class="mt-2 d-inline" action="{% url 'blog:actionDeleteArticle' article.public_id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary">Delete</button>
          </form>
        {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}
</div>
<nav aria-label="..." class="mt-1">
  <ul class="pagination justify-content-center">
    <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
      <a class="page-link" href="/{% if my %}my/{% endif %}{% if page.has_previous %}{{ page.previous_page_number }}{% endif %}">Previous</a>
    </li>
    {% if page.has_previous %}
    <li class="page-item"><a class="page-link" href="/{% if my %}my/{% endif %}{{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
    {% endif %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="#">{{ page.number }}</a>
    </li>
    {% if page.has_next %}
    <li class="page-item"><a class="page-link" href="/{% if my %}my/{% endif %}{{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
    {% endif %}
    <li class="page-item {% if not page.has_next %}disabled{% endif %}">
      <a class="page-link" href="/{% if my %}my/{% endif %}{% if page.has_next %}{{ page.next_page_number }}{% endif %}">Next</a>
    </li>
  </ul>
</nav>
{% endblock %}

blog/templates/blog/editor.html
{% extends "./base.html" %}
{% block content %}
<div class="container-sm mt-5" style="max-width: 350px">
  {% if action == 'create' %}
    <form action="{% url 'blog:actionCreateArticle' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Name</label>
        <input required type="text" autocomplete="off" name="article_name" class="form-control" id="exampleInputEmail1">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Text</label>
        <textarea maxlength="3000" rows="10" required autocomplete="off" name="article_text" class="form-control" id="exampleInputPassword1"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  {% endif %}
  {% if action == 'edit' %}
    <script>
      document.addEventListener('DOMContentLoaded', () => {
        let textarea = document.getElementById('exampleInputPassword1');
        textarea.value = `{{ article.content }}`
        console.log(textarea)
      })
    </script>
    <form action="{% url 'blog:actionEditArticle' article.public_id %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Name</label>
        <input
                required
                type="text"
                autocomplete="off"
                name="article_name"
                class="form-control"
                id="exampleInputEmail1"
                value="{{ article.name }}"
        >
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Text</label>
        <textarea
                maxlength="3000"
                rows="10"
                required
                autocomplete="off"
                name="article_text"
                class="form-control"
                id="exampleInputPassword1"
        >
        </textarea>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  {% endif %}
</div>
{% endblock %}

blog/templates/blog/profile.html
{% extends "./base.html" %}
{% block content %}
<div class="container-sm mt-5" style="max-width: 350px">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title fw-bold">{{ user.username }}</h5>
      <p class="card-text">
        number of articles: {{ stat.article_count }}
        <br>
        number of comments: {{ stat.comment_count }}
      </p>
    </div>
  </div>
  {% if profile_owner == user %}
    <form action="{% url 'blog:actionChangePassword' %}" method="post" class="mt-5">
      {% csrf_token %}
      <div class="mb-3">
        <label for="oldPassword" class="form-label">Old password</label>
        <input required type="password" name="oldPassword" class="form-control" id="oldPassword">
      </div>
        <div class="mb-3">
          <label for="newPassword" class="form-label">New password</label>
          <input required type="password" name="newPassword" class="form-control" id="newPassword">
        </div>
    <button type="submit" class="btn btn-primary">Save</button>
    </form>
    <form action="{% url 'blog:actionDeleteAccount' %}" method="post" class="mt-5">
      {% csrf_token %}
      <div class="mb-3">
          <label for="newPassword" class="form-label">Password</label>
          <input required type="password" name="password" class="form-control" id="password">
      </div>
      <button type="submit" class="btn btn-danger">Delete account</button>
    </form>
  {% endif %}
</div>
{% endblock %}

blog/templates/blog/signIn.html
{% extends "./base.html" %}
{% block content %}
<div class="container-sm mt-5" style="max-width: 350px">
  <form action="{% url 'blog:actionSignIn' %}" method="post">
    {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input required type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input required type="password" name="password" class="form-control" id="exampleInputPassword1">
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>
</div>
{% endblock %}

blog/templates/blog/signUp.html
{% extends "./base.html" %}
{% block content %}
<div class="container-sm mt-5" style="max-width: 350px">
  <form action="{% url 'blog:actionSignUp' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email address</label>
        <input required type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input required type="password" name="password" class="form-control" id="exampleInputPassword1">
      </div>
      <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
</div>
{% endblock %}